[versions]
agp = "8.5.0"
circleimageview = "3.1.0"
googleMaterial = "1.8.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.2"
constraintlayout = "2.1.4"
recyclerview = "1.3.2"
media3Common = "1.4.1"

[libraries]
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v180 = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "media3Common" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

